#!/bin/sh

#mount -t nfs -o rsize=32768,wsize=32768,intr 192.168.10.1:/data/video /media

OMXPLAYER="./omxplayer.bin"
FBSET="/usr/sbin/fbset"
FONT="fonts/FreeSans.ttf"

if [ -e /usr/share/fonts/truetype/freefont/FreeSans.ttf ]; then
  FONT="/usr/share/fonts/truetype/freefont/FreeSans.ttf"
else
  FONT="fonts/FreeSans.ttf"
fi

if [ -e /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf ]; then
  ITALIC_FONT="/usr/share/fonts/truetype/freefont/FreeSansOblique.ttf"
else
  ITALIC_FONT="fonts/FreeSansOblique.ttf"
fi

if [ -e /usr/bin/omxplayer.bin ]; then
  OMXPLAYER="/usr/bin/omxplayer.bin"
else
  OMXPLAYER="./omxplayer.bin"
fi

if [ -e /usr/lib/omxplayer ]; then
  export LD_LIBRARY_PATH=/opt/vc/lib:/usr/lib/omxplayer:$LD_LIBRARY_PATH
else
  export LD_LIBRARY_PATH=$PWD/ffmpeg_compiled/usr/local/lib:/opt/vc/lib:$LD_LIBRARY_PATH
fi

XRES=1920
YRES=1080

XRES=1600
YRES=900

if [ -e $FBSET ]; then
  echo 0 > /sys/class/vtconsole/vtcon1/bind
  fbset -xres 1 -yres 1
fi

if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval $(dbus-launch --sh-syntax)
fi

$OMXPLAYER --font $FONT --italic-font $ITALIC_FONT "$@"

if [ -e $FBSET ]; then
  fbset -xres ${XRES} -yres ${YRES}
  echo 1 > /sys/class/vtconsole/vtcon1/bind
fi
