#!/bin/sh

#mount -t nfs -o rsize=32768,wsize=32768,intr 192.168.10.1:/data/video /media

FBSET="/usr/sbin/fbset"
FONT="fonts/FreeSans.ttf"
BASE=`dirname $0`

if [ -e /usr/share/fonts/truetype/freefont/FreeSans.ttf ]; then
  FONT="/usr/share/fonts/truetype/freefont/FreeSans.ttf"
else
  FONT="fonts/FreeSans.ttf"
fi

if [ -e /usr/share/fonts/truetype/freefont/FreeSansOblique.ttf ]; then
  ITALIC_FONT="/usr/share/fonts/truetype/freefont/FreeSansOblique.ttf"
else
  ITALIC_FONT="fonts/FreeSansOblique.ttf"
fi

OMXPLAYER=$BASE"/omxplayer.bin"

if [ -e $BASE"/ffmpeg_compiled" ]; then
  export LD_LIBRARY_PATH=$PWD/ffmpeg_compiled/usr/local/lib:/opt/vc/lib:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
else
  export LD_LIBRARY_PATH=/opt/vc/lib:/usr/lib/omxplayer:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi

XRES=1920
YRES=1080

XRES=1600
YRES=900

if [ -e $FBSET ]; then
  echo 0 > /sys/class/vtconsole/vtcon1/bind
  fbset -xres 1 -yres 1
fi

OMXPLAYER_DBUS_ADDR="/tmp/omxplayer_dbus_addr"
OMXPLAYER_DBUS_PID="/tmp/omxplayer_dbus_pid"

exec 5> $OMXPLAYER_DBUS_ADDR
exec 6> $OMXPLAYER_DBUS_PID

dbus-daemon --fork --print-address 5 --print-pid 6 --session

DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`

export DBUS_SESSION_BUS_ADDRESS
export DBUS_SESSION_BUS_PID

$OMXPLAYER --font $FONT --italic-font $ITALIC_FONT "$@"; true

if [ -n "$DBUS_SESSION_BUS_PID" ]; then
    kill -2 "$DBUS_SESSION_BUS_PID"
fi

rm -f $OMXPLAYER_DBUS_ADDR
rm -f $OMXPLAYER_DBUS_PID

if [ -e $FBSET ]; then
  fbset -xres ${XRES} -yres ${YRES}
  echo 1 > /sys/class/vtconsole/vtcon1/bind
fi
